# Generated by Django 3.0.5 on 2020-04-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atracoes', '0005_auto_20200425_1543'),
        ('avaliacoes', '0001_initial'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='atracoes.Atracao', verbose_name='Atrações')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='comentarios.Comentario', verbose_name='Comentários')),
                ('evaluations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='avaliacoes.Avaliacao', verbose_name='avaliações')),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
            },
        ),
    ]
