# Generated by Django 3.0.5 on 2020-04-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='evaluations',
        ),
    ]
