# Generated by Django 3.0.5 on 2020-04-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0002_auto_20200425_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='adress',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='enderecos.Endereco', verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
