# Generated by Django 3.0.5 on 2020-05-24 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_auto_20200425_1705'),
        ('core', '0005_auto_20200524_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='enderecos.Endereco', verbose_name='Endereço'),
        ),
    ]
