# Generated by Django 3.0.5 on 2020-05-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_auto_20200425_1705'),
        ('core', '0006_auto_20200524_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='enderecos.Endereco', verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
