# Generated by Django 3.0.5 on 2020-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_avaliacao_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
