# Generated by Django 3.0.5 on 2020-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='country',
            field=models.CharField(max_length=150, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='line1',
            field=models.CharField(max_length=150, verbose_name='Linha1'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='line2',
            field=models.CharField(max_length=150, verbose_name='Linha2'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='state',
            field=models.CharField(max_length=150, verbose_name='Estado'),
        ),
    ]
