# Generated by Django 3.0.5 on 2020-04-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_auto_20200425_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
