# Generated by Django 3.0.5 on 2020-05-24 20:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_auto_20200425_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='city',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='country',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='state',
        ),
        migrations.AddField(
            model_name='endereco',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
