# Generated by Django 3.0.5 on 2020-05-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0004_auto_20200524_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='localizacao',
            new_name='location',
        ),
    ]
