# Generated by Django 3.0.5 on 2020-05-24 22:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0005_auto_20200524_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='coordenadas'),
        ),
    ]
