# Generated by Django 3.0.5 on 2020-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20200425_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
