# Generated by Django 3.0.5 on 2020-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0004_auto_20200425_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='description',
            field=models.TextField(blank=True, default=0, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atracao',
            name='min_age',
            field=models.IntegerField(default=0, verbose_name='Idade mínima'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='opening_hours',
            field=models.TextField(blank=True, verbose_name='Horario de funcionamento'),
        ),
    ]
