# Generated by Django 3.0.5 on 2020-04-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0005_auto_20200425_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atração', 'verbose_name_plural': 'Atrações'},
        ),
    ]
