# Generated by Django 3.0.5 on 2020-04-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_adress'),
        ('atracoes', '0007_atracao_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attractions', to='core.PontoTuristico', verbose_name='ponto_turistico'),
        ),
    ]
