# Generated by Django 3.0.5 on 2020-05-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0009_auto_20200427_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
